site_name: Portfolio - SÅ‚awomir Strzelec
theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md
  - About Me : o-mnie.md
  - Projects:
      - Erytrocytes: 01_erytro/index.md
      - EDA Chemoinformtics: 02_eda_chem/index.md
      - Nanotubes Simulation: 03_nanotubes/index.md
      - Raman Spectra Analyzer: 04_raman/index.md
      - Drug Solubility ML: 05_drug_solub/index.md
      - Buchwald-Hartwig C-N Coupling Optimizer: 06_reaction_opt/index.md